V1 Of Finish Screen for Payment Link Sharing
PayStell/paystell-website pull request #20
Opened 2024-11-23 15:42 UTC by CtpN3m01

# Pull Request Overview

## 📝 Summary
Provide a brief overview of what this PR accomplishes.

### 🔗 Related Issues
- Closes #(issue number) Replace with the actual issue number.

## 🔄 Changes Made
Please provide a general description of your changes. Include any relevant background information or context that may help reviewers understand the purpose of this PR.

## 🖼️ Current Output
Give evidence like screenshots of what your job looks like.

## 🧪 Testing
If applicable, describe the tests performed. Provide screenshots, test outputs, or any resources that can help reviewers understand how the changes were tested.

## 💬 Comments
Any additional context, questions, or considerations for the reviewers.

2024-11-28 17:17 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
> +            </button>
please use Button component located in components/ui for all buttons 
```suggestion
              <Button
                type="button"
                variant="default"
                onClick={() => copyToClipboard(Link, setLinkCopyMessage)}
              >
              <Copy className="w-4 h-4" />
              Copy Link
              </Button>
            
```

2024-11-28 17:18 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
> +            <button
use input component located in components/ui

2024-11-28 17:19 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
> +            </button>
same for the Button component/ui

2024-11-28 17:19 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
> +              </button>
same for the Button component/ui

2024-11-28 17:31 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
move to a separated component in `components/dashboard/links/ShareLink.tsx` follow the example of app/dashboard/links

2024-11-29 15:02 UTC, MPSxDev requested changes

2024-11-29 15:09 UTC, MPSxDev commented on paystell-frontend/src/app/payment-link/page.tsx
rigth!

2024-11-30 02:49 UTC, CtpN3m01 commented on paystell-frontend/src/app/ShareLink/page.tsx
![image](https://github.com/user-attachments/assets/847921c2-54e1-4823-99fd-e56bd9b8e8ab)

Ready

2024-12-01 00:24 UTC, MPSxDev approved these changes
excellent thanks

2024-12-01 00:25 UTC, merged