Feat/settings screen
PayStell/paystell-website pull request #28
Opened 2024-11-27 02:38 UTC by Villarley

# Pull Request Overview

## 📝 Summary
Users can:

Edit their name.
Upload or change their profile picture (with preview functionality).
Update their personal or business description.
View a responsive design suitable for different devices.
### 🔗 Related Issues
- Closes #14 

## 🔄 Changes Made
Frontend Implementation:

Designed a new SettingsScreen component using React, TailwindCSS, and Next.js.
Added components for:

1. Name input (Input).
2. Profile picture upload with real-time preview.
3. Description editor (Textarea).
4. Dynamic edit/save functionality for user convenience.
Responsive Design:

Optimized layout for mobile, tablet, and desktop screens.
Ensured seamless interaction across devices.
Error Handling:

Basic validation for required fields like Name.
Error messages displayed inline when validation fails.

## 🖼️ Current Output
![image](https://github.com/user-attachments/assets/57b7fd2a-f873-4ffd-b9bd-66ff3011a559)

## 💬 Comments
Thank you for the opportunity of contributing, looking forward to keep contributing!!

2024-11-27 16:46 UTC, MPSxDev requested changes
good job just some minor corrections

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/src/app/settings/page.tsx
> +                className="absolute bottom-0 right-0 bg-blue-500 text-white p-2 rounded-full"
use bg-primary
```suggestion
                className="absolute bottom-0 right-0 bg-primary text-white p-2 rounded-full"
```

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/src/app/settings/page.tsx
> +              </Button>
remove className, use variant 
```suggestion
              <Button
                type="button"
                variant="default"
                onClick={() => setIsEditing(true)}
              >
                Edit Profile
              </Button>
```

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/src/app/settings/page.tsx
> +                </Button>
use variant
```suggestion
                <Button
                  type="submit"
                  variant="default"
                >
                  Save
                </Button>
```

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/src/app/settings/page.tsx
> +                </Button>
use variant 
```suggestion
                <Button
                  type="button"
                  variant="destructive"
                  onClick={() => setIsEditing(false)}
                >
                  Cancel
                </Button>
```

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/package-lock.json
remove file package-lock.json

2024-11-27 16:46 UTC, MPSxDev commented on paystell-frontend/package.json
> +    "shadcn-ui": "^0.9.3",
Update 2 high severity vulnerabilities
```suggestion
    "shadcn-ui": "^0.2.3",
```

2024-11-28 01:18 UTC, MPSxDev requested changes

2024-11-28 01:18 UTC, MPSxDev commented on paystell-frontend/src/app/settings/page.tsx
add the content to the new file deployed in dashboard/settings

2024-11-28 02:51 UTC, Villarley commented
@MPSxDev ready sir!

2024-11-28 13:59 UTC, MPSxDev approved these changes
Great job. Thanks @Villarley

2024-11-28 13:59 UTC, merged